exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - script
  - src

remote_theme: marella/jekyll-theme-documentation

permalink: pretty
nav:
  - Getting Started:
    - Introduction: ''
  - Installation:
    - Anaconda3: demos/anaconda3
    - Another Page: demos/another-page
    - Table of Contents: demos/toc
